{% set name = "aldjemy" %}
{% set version = "0.7.0"%}
{% set sha256 = "2282c5cc68a82b145fd0a536c910d4c6f27302a340df0251352ae1798d7a9299" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - sqlalchemy >0.7.1

test:
  imports:
    - aldjemy

  commands:
    - 'cd test_project; python manage.py test'  # [not win]
    - 'cd test_project & python manage.py test'  # [win]

  requires:
    # django 1.11 yields
    # ImportError: No module named test1.urls 
    - django <1.11
    - django-extensions
    - sqlalchemy >0.7.1

  source_files:
    - test_project

about:
  home: https://github.com/Deepwalker/aldjemy/
  license: BSD
  license_family: BSD
  # To be added https://github.com/Deepwalker/aldjemy/pull/50
  # license_file: LICENSE
  summary: 'SQLAlchemy to Django integration library'
  dev_url: https://github.com/Deepwalker/aldjemy

extra:
  recipe-maintainers:
    - ltalirz
