{% set name = "aldjemy" %}
{% set version = "2.0" %}
{% set sha256 = "4dbaa71e99f305fb3c47420084c5f26d6cc43732594057e04822b2db063528d1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry

  run:
    - python >=3.6
    - sqlalchemy >=1.4
    - django >=2.2

test:
  imports:
    - aldjemy

  requires:
    - django-extensions
    - psycopg2-binary
    - poetry

  commands:
    - poetry run ./test.sh

  source_files:
    - test.sh
    - test_project
    - test_project_postgres

about:
  home: https://github.com/aldjemy/aldjemy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy for your Django models
  dev_url: https://github.com/aldjemy/aldjemy

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
