{% set name = "aldjemy" %}
{% set version = "0.9.0" %}
{% set sha256 = "4dc07ad4f30fca42529fdbc6d7350329c5ca6517d842e618146f4ca445c19a13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip

  host:
    - python
    - pip

  run:
    - python
    - sqlalchemy >0.7.1

test:
  imports:
    - aldjemy

  commands:
    - 'cd test_project; python manage.py test'  # [not win]
    - 'cd test_project & python manage.py test'  # [win]

  requires:
    - django
    - django-extensions
    - sqlalchemy >0.7.1

  source_files:
    - test_project

about:
  home: https://github.com/Deepwalker/aldjemy/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: 'SQLAlchemy to Django integration library'
  dev_url: https://github.com/Deepwalker/aldjemy

extra:
  recipe-maintainers:
    - ltalirz
