{% set name = "aldjemy" %}
{% set version = "1.0.0" %}
{% set sha256 = "38ef5914e8d93cd19b0d6059b6963007445dd153622ea0b35901b91b8ca3d79a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python
    - sqlalchemy >0.7.1

test:
  imports:
    - aldjemy

  commands:
    - cd test_project
    - python manage.py test

  requires:
    - django >=2.2
    - django-extensions
    - sqlalchemy >0.7.1

  source_files:
    - test_project

about:
  home: https://github.com/Deepwalker/aldjemy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy to Django integration library
  dev_url: https://github.com/Deepwalker/aldjemy

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
