{% set name = "aldjemy" %}
{% set version = "2.2" %}
{% set sha256 = "6c8215164a983117b4a3c28a43cec7ab7b564c938b6fe4797a970edd8a35cc9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry

  run:
    - python >=3.6
    - sqlalchemy >=1.4
    - django >=2.2

test:
  imports:
    - aldjemy

about:
  home: https://github.com/aldjemy/aldjemy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: SQLAlchemy for your Django models
  dev_url: https://github.com/aldjemy/aldjemy

extra:
  recipe-maintainers:
    - ltalirz
    - chrisjsewell
