travis:
  secure:
    BINSTAR_TOKEN: kMNdZ5GRYRhNEL/s2G1FYh1g+sT0kWrdp5tugJzIuuobYiDPt3pXeK9O27TZOnfOar2Bp7tFNIsf8ln08K2Pqz+uHIv+lFqNxQPmFjmHGPit7eGSEABLaMqcofWjXYSQN0yroKI0DxX0uzKtpa1FMsMXI7MyRBNeeweuQNiYVBx0FYOuCCVEOL9FiBP5vwBSYuh9gAnAiRjtvvaoZbquqh+sFXyIjJA6FN3pCB1kMBDe5h5sx3t3vunrrVSBGS5Jh5Ryr27g0CnH0j7zAGPZ/jr8TpeIHsKfYOF63VkVyc/FbpEiKJs7TfCWBwwdG2Crc/BxRgUNcBztDJppQ3XpiU2m7pweMBr2Xu48qvF3P5cLKUciDBZXtqa0cbG5BMVEjnbtE8iQNkJY/bJpCdnrpmAvhCOx+oeEwEJ2zxQAiKfvo+lunpgcyDDZCZphA39QYHk1oKgE0wBBNIazBSNd0QqRFL9fpwcl9RPUB9Jfa581110cF6HVbxTfd7aFkJC3/IqjAPl7jwod+SfLnnWQd4Jn3FAjLia2dL97Pm8HzrhB+wjfq55ktCP3fgccrWLHo9vH3nSp8+cXifjKOHdad/miMNtUAweloN6tR2Y2jCVFOLLhOWMzoisjPH+mB7SVpc5kQ2EekoAQDYQZCR3719YMc4ITtLyGgJXiom9NmIA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
