travis:
  secure:
    BINSTAR_TOKEN: ReEKj7Kj6coZxveavRT9KUB+rxvMbpThmP8MTbyKqhn25RiutBP/WOXHtN9WwnTQN5rv7VcbZBzegRsJxJGsTEwSE3efY4WCpm0gzheDjqC1MJFUbs6vgG8M1+ij57/RMCzDsOKdi3QXR/4XpLhrCHtV7nYhn4+G0/qCM4EcIvFfdwYGe+KonEVtLQgfeTJByVVrqdD5c2kJYxO8RQxZtHxCaMyzbHVPqQT3BDyjngEf7RFpaM9qeZTKpJ3OS+Ke44bhZ2CqDtxyTcu5IzEu/JWS/r/1XFAvnjTmHuHAip4SGXqazv6+/ErQ8k+yUWWBMGJOvq3/Q8CLGbHBC13Qi2tB6yxNkbLuLL4wzy6qEvVEVMnoWO6PutjVtIVBg/Vp04pFN8bUmtZBU4HKv3H8VZDBfjZs3GONGbT4C5vWpINhFfQ5VFFu8ZcZ2clIRZLHcucTQ4q/HcGO3xyw6wc2hpLLfVUWsAPk8NHn3kqj3hDvZtpaTkdXeEh3J/zbfeTLxIDmFYdHNhS+WkI6y+6ufeOoSShggK+2ur4GKjLXfqeu+iq6yRMf1NAuaDO9l3uyguN3Hq4u2+nprsAwUnG1TQ8Mbe5HRefS4Zf3YsBROWZG8AqMQUG7lH617b8OKRbnvkO88U8BkGlBD1pKskX0lZbOVdMdJWY8UG6OmJVtB14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
