appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GTtXUQjYprdkcn6HrFa/aOZi0Y9InsQuZDTGhFov6h2OV5Hw8eGAVN61oiOLd/ycMRjGEHUoedezHlzFFP3G3BS+bQWf6dC1hqQmtdrrCqDBqM0Tj4Ngk6rWs5ZGGK/aikIkBkZTjMEYJ70CkMIgM/XXa9Bl+ljOdSWcGso2Qe92FUVAYzpx8lHVh7dwZDHWYu2qtwTEhxgJkwblgpFW6XvMA4m30/EHcbl2zC3xwoiiGdzGjBWmxn+YWzl7kSViaFLosL6uxPL9uH8g5olW2BuS4e+L2veD16U+frRtknsf3L7y7eNT1pznXpXOYRIuJ46DwReOEnABfBtHxyMhLvNnEpmUwDPA1jkQGS+QkZCSgJhH269eUJ4srDNKRVVs1rdy1CNJ6M5BQZfxeATzrP60YfhlF968NL27g50UGrmwxwQdKbcZdCB5HMxbHTgI7yKuMWFv3U/zV/AYzNFVNDaIQy1rSue93lxyrzSjHykL1TfxkmR9QOBdZzFZjB841uzdcWq2MFsUYoqfDMEtm/K6mVL0yd5fklXWeKau0BWKYZdUL0vN34L+tIQ25nLWHC1OuI7rUj8js6LxQBlTWO2SmSTIciXmHrOv9y7mt78VOHFC36xcBDmd8Is0ESi873H4/PjaK/ptFF8zXNT26UTMv2c3Ev5HAmX+0rkBlq0=}
provider:
  win: azure
